spring:
  security:
    oauth2:
      client:
        registration:
          kakao:
            provider-id: kakao
            client-id: badc5116e1e1430d0e0d5a76a9ebe3a7
            client-secret: f7NudsPDj0WqIwK5H9ZZCiXCfpqwU8q9

  mail:
    host: smtp.gmail.com
    port: 587
    username: hyeonjae1023111@gmail.com
    password: inyi qmds uizx vxta
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: